version: '3.8'

services:
  frontend-web:
    build: ./spotmusic-frontend-web
    ports:
      - "80:80"
    networks:
      - spotmusic-network

  frontend-app:
    build: ./spotmusic-frontend-app
    ports:
      - "8081:8081" 
    networks:
      - spotmusic-network

  backend:
    build: ./spotmusic-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=spotmusic
    networks:
      - spotmusic-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=spotmusic
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - spotmusic-network

networks:
  spotmusic-network:
    driver: bridge

volumes:
  db_data:
